spring:
  cloud:
    gateway:
      routes:
        - id: CUSTOMERS
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
        - id: PRODUCTS
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/products/**
    config:
      enabled: false
    discovery:
      enabled: true
  application:
    name: gateway-service

server:
  port: 8888

eureka:
  client:
    service-url:
     default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true